build_gcp-intouch-generate-guarantee:
  stage: build
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || ($CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'master')"
      changes:
        - applications/intouch/functions/gcp-generate-guarantee/**/*
  needs:
    - install
  before_script:
    - yarn config set cache-folder ~/.yarn
  script:
    - yarn workspace @bmi/gcp-intouch-generate-guarantee run build
  artifacts:
    paths:
      - applications/intouch/functions/gcp-generate-guarantee/dist

package_gcp-intouch-generate-guarantee:
  stage: package
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'master'"
      changes:
        - applications/intouch/functions/gcp-generate-guarantee/**/*
  needs:
    - build_gcp-intouch-generate-guarantee
  dependencies:
    - build_gcp-intouch-generate-guarantee
  before_script:
    - apt-get update
    - apt-get install -y zip unzip
    - mkdir -p dist/applications/intouch/functions
    - NPM_AUTH_READ_TOKEN=$NPM_AUTH_READ_TOKEN
  script:
    - cd applications/intouch/functions/gcp-generate-guarantee
    - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_READ_TOKEN}">.npmrc
    - zip -r $CI_PROJECT_DIR/dist/applications/intouch/functions/gcp-generate-guarantee.zip .npmrc .yarnrc package.json dist/
    - cd $CI_PROJECT_DIR
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/applications/intouch/functions

# Deploy to QA
deploy_gcp-intouch-generate-guarantee:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk
  stage: deploy
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'master'"
      changes:
        - applications/intouch/functions/gcp-generate-guarantee/**/*
      allow_failure: true
  needs:
    - package_gcp-intouch-generate-guarantee
  dependencies:
    - package_gcp-intouch-generate-guarantee
  before_script:
    - |
      GCP_INTOUCH_REPLATFORM_SERVICE_KEY=$GCP_INTOUCH_REPLATFORM_SERVICE_KEY
      GCP_INTOUCH_REPLATFORM_PROJECT_ID=$GCP_INTOUCH_REPLATFORM_PROJECT_ID
      GCP_INTOUCH_REPLATFORM_BUILD_STORAGE=$GCP_INTOUCH_REPLATFORM_BUILD_STORAGE

      INTOUCH_MAIL_FROM=$INTOUCH_MAIL_FROM
      GCP_SECRET_PROJECT=$GCP_SECRET_PROJECT
      GCP_PRIVATE_BUCKET_NAME=$GCP_PRIVATE_BUCKET_NAME
      INTOUCH_GATEWAY_API_URL=$INTOUCH_GATEWAY_API_URL
  script:
    - echo $GCP_INTOUCH_REPLATFORM_SERVICE_KEY > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_INTOUCH_REPLATFORM_PROJECT_ID
    - gsutil cp $CI_PROJECT_DIR/dist/applications/intouch/functions/gcp-generate-guarantee.zip gs://$GCP_INTOUCH_REPLATFORM_BUILD_STORAGE/
    - gcloud builds submit . --config=applications/intouch/functions/gcp-generate-guarantee/cloudbuild.yaml --substitutions _GCP_INTOUCH_REPLATFORM_BUILD_STORAGE=$GCP_INTOUCH_REPLATFORM_BUILD_STORAGE,_INTOUCH_MAIL_FROM=$INTOUCH_MAIL_FROM,_GCP_SECRET_PROJECT=$GCP_SECRET_PROJECT,_GCP_PRIVATE_BUCKET_NAME=$GCP_PRIVATE_BUCKET_NAME,_NPM_AUTH_READ_TOKEN=$NPM_AUTH_READ_TOKEN,_INTOUCH_GATEWAY_API_URL=$INTOUCH_GATEWAY_API_URL
