test_contentful-default-values:
  extends: .test_yarn_workspace
  rules:
    - !reference [.ingore_release_mrs, rules]
    - if: !reference [.run_for_changes_on_main, rules, if]
      changes:
        - $ROOT_DIR/**/*
        - jest/**/*
        - yarn.lock
        - applications/dxb/libraries/cms-consolidation-utility/**/*
    - if: !reference [.run_for_changes_on_mr, rules, if]
      changes:
        - $ROOT_DIR/**/*
        - jest/**/*
        - yarn.lock
        - applications/dxb/libraries/cms-consolidation-utility/**/*
  variables:
    WORKSPACE: "@bmi/contentful-default-values"
    ROOT_DIR: "applications/functions/contentful-default-values"

build_contentful-default-values:
  extends: .build_function
  rules:
    - !reference [.ingore_release_mrs, rules]
    - if: !reference [.run_for_changes_on_main, rules, if]
      changes:
        - $ROOT_DIR/**/*
        - yarn.lock
        - applications/dxb/libraries/cms-consolidation-utility/**/*
    - if: !reference [.run_for_changes_on_mr, rules, if]
      changes:
        - $ROOT_DIR/**/*
        - yarn.lock
        - applications/dxb/libraries/cms-consolidation-utility/**/*
    - if: !reference [.run_for_preprod_release, rules, if]
    - if: !reference [.run_for_prod_release, rules, if]
  variables:
    WORKSPACE: "@bmi/contentful-default-values"
    ROOT_DIR: "applications/dxb/functions/contentful-default-values"

package_contentful-default-values:
  extends: .package_function
  needs:
    - job: build_contentful-default-values
      artifacts: true
  rules:
    - if: !reference [.run_for_changes_on_main, rules, if]
      changes:
        - $ROOT_DIR/**/*
        - yarn.lock
        - applications/dxb/libraries/cms-consolidation-utility/**/*
    - if: !reference [.run_for_preprod_release, rules, if]
    - if: !reference [.run_for_prod_release, rules, if]
  variables:
    FUNCTION_NAME: "contentful-default-values"
    ROOT_DIR: "applications/dxb/functions/contentful-default-values"

deploy_contentful-default-values:
  extends: .deploy_function
  needs:
    - job: package_contentful-default-values
      artifacts: true
  rules:
    - if: !reference [.run_for_changes_on_main, rules, if]
      changes:
        - $ROOT_DIR/**/*
        - yarn.lock
        - applications/dxb/libraries/cms-consolidation-utility/**/*
      variables:
        GCP_FUNCTIONS_CI: $GCP_FUNCTIONS_CI_QA
    - if: !reference [.run_for_preprod_release, rules, if]
      variables:
        GCP_FUNCTIONS_CI: $GCP_FUNCTIONS_CI_PREPROD
    - if: !reference [.run_for_prod_release, rules, if]
      variables:
        GCP_FUNCTIONS_CI: $GCP_FUNCTIONS_CI_PROD
  variables:
    FUNCTION_NAME: "contentful-default-values"
    ROOT_DIR: "applications/dxb/functions/contentful-default-values"
